-- Adds `redo_stack`, the mirror of `undo_stack` for the redo feature.
--
-- WHY THIS ISN'T THE AUTOGENERATED SQL
--
-- drizzle-kit's raw output for this diff also emitted a 12-step rebuild of
-- `availability`, `people`, `settings`, `shifts` and `undo_stack` (create
-- __new_x, copy, drop, rename) even though none of their columns changed.
-- That rebuild drops `people`, a foreign-key parent of `availability`, and
-- `PRAGMA foreign_keys=OFF` is a no-op inside the transaction Drizzle's
-- migrator wraps every migration in — so the drop would cascade and wipe
-- `availability` (and, transitively, `assignments`). This is the exact bug
-- migration 0003 was rewritten to avoid; the fix here is the same: nothing
-- but the new table is touched.
CREATE TABLE `redo_stack` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`schedule_id` integer DEFAULT 1 NOT NULL,
	`label` text NOT NULL,
	`snapshot` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX `redo_schedule_idx` ON `redo_stack` (`schedule_id`);
